### ISSUE TITLE
Create a DataSequence pipeline

### ISSUE THREAD

**Issue by fatmai** [machine-shop/music-features#6]

**Comment by stefanv** [comment]
Can you expand a bit on this issue?

**Comment by fatmai** [comment]
This is a class that we are currently using to store stimulus-related methods and attributes. It would be nice to convert the current features class (features.py) to this class. We can discuss next time what the best way would be to handle this sort of code updating issue.

**Comment by fatmai** [comment]
after consulting with @stefanv I decided not to pursue this for the music features to make this standalone. so closing this issue.
